from typing import Optional
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.core.security import get_current_user
from app.models.user import User
from app.schemas.chat_schema import (
    ChatRequest,
    ChatResponse,
    RegenerateRequest,
    MessageFeedbackRequest,
    MessageFeedbackResponse,
    MemoryDebuggerResponse
)
from app.services.chat_service import ChatService
from app.services.context_service import ContextService
from app.services.llm_service import ConfigurationError, LLMProviderError
from app.core.logging_config import logger

router = APIRouter(prefix="/chat", tags=["Chat"])

@router.post("", response_model=ChatResponse, status_code=status.HTTP_200_OK)
def send_chat_message(
    request: ChatRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Primary authenticated multi-turn chat endpoint:
    - Retains conversation context for authenticated user
    - Injects long-term memory
    - Injects conversation summary & keywords
    - Context-window truncation and auto-summarization
    - Auto-extracts new persistent facts
    """
    clean_msg = request.message.strip()
    if not clean_msg:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Message content cannot be empty."
        )

    try:
        service = ChatService(db)
        return service.process_chat_message(
            user_id=current_user.id,
            message=clean_msg,
            conversation_id=request.conversation_id,
            attachment_ids=request.attachment_ids,
            language=request.language
        )
    except HTTPException:
        raise
    except ConfigurationError as e:
        logger.error(f"LLM Configuration Error: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )
    except LLMProviderError as e:
        logger.error(f"LLM Provider Error: {e}")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Zara couldn't reach the AI service. Please check your connection or try again."
        )
    except Exception as e:
        logger.exception(f"Unexpected chat processing error: {e}")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Zara couldn't reach the AI service. Please check your connection or try again."
        )

@router.post("/stream")
def send_chat_message_stream(
    request: ChatRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Real-time streaming response endpoint via Server-Sent Events (SSE).
    Streams chunks as generated by the provider and persists final state.
    """
    clean_msg = request.message.strip()
    if not clean_msg:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Message content cannot be empty."
        )

    service = ChatService(db)
    generator = service.process_chat_message_stream(
        user_id=current_user.id,
        message=clean_msg,
        conversation_id=request.conversation_id,
        attachment_ids=request.attachment_ids,
        language=request.language
    )

    return StreamingResponse(
        generator,
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"
        }
    )

@router.post("/regenerate", response_model=ChatResponse, status_code=status.HTTP_200_OK)
def regenerate_response_endpoint(
    request: RegenerateRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Regenerates the specified assistant response (or the last response in thread)
    without duplicating user messages.
    """
    service = ChatService(db)
    return service.regenerate_response(
        user_id=current_user.id,
        conversation_id=request.conversation_id,
        message_id=request.message_id
    )

@router.post("/feedback", response_model=MessageFeedbackResponse, status_code=status.HTTP_200_OK)
def submit_feedback_endpoint(
    request: MessageFeedbackRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Records or updates user feedback (like / dislike) for an assistant message.
    """
    service = ChatService(db)
    res = service.record_feedback(
        user_id=current_user.id,
        message_id=request.message_id,
        feedback=request.feedback
    )
    return MessageFeedbackResponse(**res)

@router.get("/debug-context", response_model=MemoryDebuggerResponse)
def get_memory_debug_context(
    conversation_id: Optional[str] = None,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Developer-oriented endpoint for Memory Debugger.
    Returns assembled system prompt, user preferences, long-term memories,
    summary, keywords, and context usage without exposing API keys or secrets.
    """
    context_service = ContextService(db)
    data = context_service.get_debug_context(
        conversation_id=conversation_id,
        user_id=current_user.id
    )
    return MemoryDebuggerResponse(**data)
